#!/bin/bash
#
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 kasutajanimi"
elif [ ! -d $public ]; then
	mkdir $public
	chmod -R 751 $public
	echo "<html><body>Teretulemast, $kasutaja</body></html>" > $public/index.html
	chown -R $kasutaja:www-data $public
	sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf
	a2enmod userdir
	service apache2 restart
else
	echo "kontrollin õigused"
	if [ "stat -c "%a" $public" != 751 ]; then
		echo "õigused on valed"
		chmod -R 751 $public
		chown -R $kasutaja:www-data $public
		echo "õigused muudetud õigeks"
	if [ $? -eq 0 ]; then
		echo "veebilehele saab minna aadressiga: http://172.23.13.43/~$kasutaja/index.html"
fi
fi
fi
