#!/bin/bash
#
if [ $# -ne 2 ]; then
	echo "Kasutusjuhend: $0 fail1 fail2"
else
	fail1=$1
	fail2=$2

	if [ -f $fail1 -a -r $fail1 ] && [ -f $fail2 -a -r $fail2 ]; then
		echo "failid on ok"
	paste -d ":" $fail1 $fail2 > temp
	for rida in $(cat temp)
	do
		kasutajanimi=$(echo "$rida" | cut -f1 -d:)
		useradd $kasutajanimi -m -s /bin/bash
		echo "$rida" | chpasswd
		echo "$kasutajanimi on lisatud"
	done
	else
		echo "viga failis $fail1 või $fail2"
	fi
	rm temp
fi
