#!/bin/bash
#
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 failinimi"
else
	failinimi=$1
	if [ -f $failinimi -a -r $failinimi ]; then
		echo "fail on korras"
		for rida in $(cat $failinimi)
		do
			kasutajanimi=$(echo "$rida" | cut -f1 -d:)
			sh lisa_kasutaja $kasutajanimi
		done
	fi
	failinimi=$2
	if [ -f $failinimi -a -r $failinimi ]; then
		echo "parooli fail on korras"
		for rida in $(cat $failinimi)
		do
			parool=$(echo "$rida" | cut -f1 -d:)
			sh paroolid $parool
		done
else 
	"echo probleem failiga $failinimi"
	fi
fi
